import "./blocks/icon-block";
// import './blocks/test-block';
import "./blocks/service-section";
import "./blocks/pricing-table";
import "./blocks/progress-bar";
import "./blocks/progress-bar-pie";
import "./blocks/zita-block-slider";
import "./blocks/post-list-layout";
import "./blocks/zita-post-slider";
import "./blocks/post-category-layout";
import "./blocks/post-image-layout";
import "./blocks/post-grid-layout";
