import "./blocks/icon-block";
// import './blocks/test-block';
import "./blocks/service-section";
import "./blocks/pricing-table";
import "./blocks/progress-bar";
import "./blocks/progress-bar-pie";
import "./blocks/zita-block-slider";
import "./blocks/post-grid-layout";
import "./blocks/post-list-layout";
import "./blocks/zita-post-slider";
import "./blocks/post-category-layout";
import "./blocks/post-image-layout";
import "./blocks/post-image-layout-two-post";
import "./blocks/post-image-layout-three-post";
import "./blocks/post-image-layout-four-post";
import "./blocks/post-image-layout-five-post";
import "./blocks/post-image-layout-six-post";
// layout block 
// import "./blocks/block-layout";
import "./blocks/block-layout-pre";
